### ISSUE TITLE
Confirmed: working on UE55JS8500

### ISSUE THREAD

**Issue by twistedpixel** [tdudek/samsung-remote-models-2014-and-newer#1]
Got excited so tried it immediately. Connected, pin request appeared, accepted and paired. Commands from your demo worked but had to use Power rather than Power Off to turn it off.

Sadly cannot Power on from standby as the network adapter shuts down completely on European TVs due to some regulatory nonsense. Can you confirm that is the case with yours?

Great work by the way. I will test with my other Samsung as soon as I can. It’s a 2016 but can’t remember model number off the top of my head - it uses the slightly newer auth method which will be useful for you to confirm further compatibility.

**Comment by tdudek** [comment]
Awesome, glad to hear it works not only with my device :) 👍 Thank you for your feedback. 
I will put your device on the list of the working TVs.

As long as I know the power off may differ between the models 2014 and 2016+. I had to try both and I've decided to leave the one which was working here in the demo ;)

Too bad about the power on from standby. I can confirm the same behavior here. At least you have an explanation, why the network adapter shuts down completely. I tried to use wake on LAN without any success. I hope there will be an other solution but some IR blaster to power on the TV. Any ideas?

**Comment by twistedpixel** [comment]
No problem, I’m happy to test further as necessary.

Yeah sucks about the standby issue. I tried with WOL as well which didn’t work on my LG or JS8500 but strangely, the 2016 Samsung (which, again I forget the model... KS7500 maybe?) stays connected to Wi-Fi for around 10 minutes into standby. I thought it was working because WOL worked after I turned it off but then I realized it turned off completely shortly after. It doesn’t even work when wired by Ethernet!!

IR blaster is probably the best solution but as someone who likes tinkering with code, it feels kind of like cheating!

Someone mentioned a Raspberry Pi connected via HDMI and then use HDMI-CEC commands to power it on. Which is cool but not many TVs power their USB ports in standby. None of mine do. So you’d need yet another cable somewhere.

In the end, I think IR will be the most compatible solution. I preordered the Sevenhugs Smart Remote and I’m hoping it will be a futuristic version of Logitech’s Harmony devices. It seems to support IFTTT and an HTTP API (please be JSON, please be JSON...) so I’m excited to try it.

I think maybe the reason that there are two Power commands in Samsung API is that USA/Canadian and potentially other areas are not restricted by this stupid low-energy-standby regulation so they stay connected. Perhaps the one that doesn’t work is in fact “Power on”. I would leave it in because someone may be able to confirm it working with one of those models.

Anyway, I will test the other Samsung tomorrow evening and let you know what the results are. In fact, I may be able to confirm the power on thing since, as I said: this one appears to stay connected for a short while into standby.

**Comment by riemers** [comment]
If you have a receiver, it usually turns on the tv too when you turn that on. My receiver works via network too. I find hdmi cec with a rasperry pi to not always work 100%

**Comment by twistedpixel** [comment]
I have a Sony receiver and Sony are notorious for their closed APIs. Sadly, it cannot be automated :(

**Comment by paolog89** [comment]
It works as above for Samsung UE48H6270
