### ISSUE TITLE
Confirmed: working on UE48JS9000

### ISSUE THREAD

**Issue by Iniaki** [tdudek/samsung-remote-models-2014-and-newer#12]
Thank you!
Could be nice to have the same for Android

**Comment by tdudek** [comment]
thx for contribution :+1: 

there might be some comprehensive project for Android, I didn't check out :-)

**Comment by simoa** [comment]
Hi @Iniaki,

We have an Android app for Remote Control. We would like to try if it's working on the J models. Can we add you to the beta testing please?

Thanks very much

Simo
